/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context } from "./src/context"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  MakeDishInput: { // input type
    dishType: NexusGenEnums['DishType']; // DishType!
    image?: string | null; // String
    ownerId?: number | null; // Int
    rating: NexusGenEnums['RatingType']; // RatingType!
    title: string; // String!
  }
  UpdateDishInput: { // input type
    dishType?: NexusGenEnums['DishType'] | null; // DishType
    id?: number | null; // Int
    image?: string | null; // String
    rating?: NexusGenEnums['RatingType'] | null; // RatingType
    title?: string | null; // String
  }
}

export interface NexusGenEnums {
  DishType: "DESSERT" | "MAIN" | "SIDE" | "STARTER"
  RatingType: "FIVE" | "FOUR" | "ONE" | "THREE" | "TWO"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Dish: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    dishType: NexusGenEnums['DishType']; // DishType!
    id: number; // Int!
    image?: string | null; // String
    rating: NexusGenEnums['RatingType']; // RatingType!
    title: string; // String!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Dish: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    dishType: NexusGenEnums['DishType']; // DishType!
    id: number; // Int!
    image: string | null; // String
    rating: NexusGenEnums['RatingType']; // RatingType!
    title: string; // String!
  }
  Mutation: { // field return type
    createDish: NexusGenRootTypes['Dish'] | null; // Dish
    updateDish: NexusGenRootTypes['Dish'] | null; // Dish
  }
  Query: { // field return type
    dishById: NexusGenRootTypes['Dish'] | null; // Dish
    dishes: Array<NexusGenRootTypes['Dish'] | null>; // [Dish]!
    filterDishes: Array<NexusGenRootTypes['Dish'] | null> | null; // [Dish]
  }
}

export interface NexusGenFieldTypeNames {
  Dish: { // field return type name
    createdAt: 'DateTime'
    dishType: 'DishType'
    id: 'Int'
    image: 'String'
    rating: 'RatingType'
    title: 'String'
  }
  Mutation: { // field return type name
    createDish: 'Dish'
    updateDish: 'Dish'
  }
  Query: { // field return type name
    dishById: 'Dish'
    dishes: 'Dish'
    filterDishes: 'Dish'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createDish: { // args
      MakeDishInput: NexusGenInputs['MakeDishInput']; // MakeDishInput!
    }
    updateDish: { // args
      updateDishInput: NexusGenInputs['UpdateDishInput']; // UpdateDishInput!
    }
  }
  Query: {
    dishById: { // args
      id?: number | null; // Int
    }
    filterDishes: { // args
      searchString?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}